version: '3.3'

services:

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    image: konebachirou/app
    depends_on:
      - mongodb
    networks:
      - uvicorn_network

  mongodb:
    image: mongo:4.4.19
    ports:
      - "27017:27017"
    networks:
      - uvicorn_network

  seed_mongo:
    build:
     context: ./seed
     dockerfile: Dockerfile
    depends_on:
      - mongodb
    image: konebachirou/seed
    networks:
      - uvicorn_network

networks:
  uvicorn_network:
    driver: bridge